### ISSUE TITLE
[Wow] Untitled

### ISSUE THREAD

**Issue by ioworker0** [cch123/bottlenecks-go#1]
Dude, I could hardly wait to read the posts! 
So, please update as soon as possible. LOL!

**Comment by buffge** [comment]
你甚至不是第一个watch的 @Mutated1994

**Comment by ioworker0** [comment]
> 你甚至不是第一个watch的 @Mutated1994

第一个不重要，重要的是对的时间对的人😃

**Comment by cch123** [comment]
淡定，我还在想要英语写还是中文。。

**Comment by buffge** [comment]
> 淡定，我还在想要英语写还是中文。。

我觉得看的国人比较多,我希望是中文,专业名词用英文

**Comment by ioworker0** [comment]
> 淡定，我还在想要英语写还是中文。。

我觉得还是中英两版吧，个人比较喜欢英文版。

**Comment by cch123** [comment]
可以，我尽量
估计会一堆语法错误哈哈 orz

**Comment by ioworker0** [comment]
> 可以，我尽量
> 估计会一堆语法错误哈哈 orz

这才有那味，吼吼z~
